#!/bin/sh

# Source tutorial clean functions
. $WM_PROJECT_DIR/bin/tools/CleanFunctions

cleanCase
rm -f constant/polyMesh/boundary
rm -f postProcess.txt
rm -r dynamicCode
rm -r constant/setSubset
rm -r system/setSubset
rm -r 0/setSubset
